# config/application.yml
defaults: &defaults
  mapbox:
    url: 'https://api.mapbox.com' 
    api_token: 'sk.eyJ1IjoiYnJvd3NlcmlubyIsImEiOiJjamEzdjBxOGM5Nm85MzNxdG9mOTdnaDQ0In0.tMMxfE2W6-WCYIRzBmCVKg'

development:
  <<: *defaults
  database:
    adress:
      - '127.0.0.1:27030'
    name: 'Ampere'

test:
  <<: *defaults

production:
  <<: *defaults
  database:
    adress:
      # - '127.0.0.1:27030'
      - '10.130.96.220:27018'
      # - '10.130.96.220:27019'
      # - '10.130.96.144:27018'
      # - '192.168.0.102:27018'
    name: 'Ampere'
