---
plugins:
- runtime
include:
- "**/*.rb"
exclude:
- .rblcl/**/*
- spec/**/*
- test/**/*
- vendor/**/*
- .git/**/*
- .logs/**/*
require: []
domains: []
reporters:
- rubocop
- require_not_found
max_files: 5000
