# frozen_string_literal: true

# bootstrap Bundler: consente `rake <task>` senza `bundle exec`
# (gemme risolte dal Gemfile.lock di questo progetto)
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('Gemfile', __dir__)
require 'bundler/setup'

task :environment do
  ENV['RACK_ENV'] ||= ARGV[1] || 'development'
  ARGV.clear

  require_relative './server'
end

desc 'Start REPL session (short-cut alias: "c")'
task console: :environment do
  if defined?(Pry)
    Pry.start
  else
    require 'irb'
    IRB.start
  end

  exit!(0)
end

task c: :console
task pry: :console

# Avvio in FOREGROUND con Ctrl-C funzionante: Puma parte in-process (Puma::CLI),
# la catena e' solo shell -> ruby, senza gli strati mise/cmd che su Windows
# restano appesi dopo il Ctrl-C. Uso: cd server && bundle exec rake server_dev
desc 'Avvia il server di sviluppo in foreground su :9292 (Ctrl-C per fermare)'
task :server_dev do
  require 'puma/cli'
  Puma::CLI.new(['--port', '9292']).run
end

desc 'Avvia lo stack di produzione in foreground, Puma SSL + Caddy (Ctrl-C per fermare)'
task :server_prod do
  require 'puma/cli'
  Puma::CLI.new(['-C', 'config/puma_prod.rb']).run
end

begin
  require 'rspec/core/rake_task'
  require 'rubocop/rake_task'

  RSpec::Core::RakeTask.new(:spec)
  RuboCop::RakeTask.new

  # rubocop entrerà nel default quando le offense esistenti saranno azzerate
  task default: :spec
rescue LoadError
  # gemme di sviluppo assenti (es. produzione): niente task spec/rubocop
end

# Dir.glob('./lib/tasks/**/*.rake').each { |task| load(task) }
