# frozen_string_literal: true

task :environment do
  ENV['RACK_ENV'] ||= ARGV[1] || 'development'
  ARGV.clear

  require_relative './server'
end

desc 'Start REPL session (short-cut alias: "c")'
task console: :environment do
  if defined?(Pry)
    Pry.start
  else
    require 'irb'
    IRB.start
  end

  exit!(0)
end

task c: :console
task pry: :console

begin
  require 'rspec/core/rake_task'
  require 'rubocop/rake_task'

  RSpec::Core::RakeTask.new(:spec)
  RuboCop::RakeTask.new

  # rubocop entrerà nel default quando le offense esistenti saranno azzerate
  task default: :spec
rescue LoadError
  # gemme di sviluppo assenti (es. produzione): niente task spec/rubocop
end

# Dir.glob('./lib/tasks/**/*.rake').each { |task| load(task) }
